config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "cocktails#index"
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
  resources :ingredients, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
end

# how to depend destory ingredient when deleting cocktail unless not used elsewhere?
# how to create uniqu pair condition

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, presence: true
  validates :cocktail, presence: true
  validates :ingredient, presence: true
  validates :ingredient_id, uniqueness: { scope: :cocktail_id }
  belongs_to :ingredient
  belongs_to :cocktail
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, uniqueness: true
  validates :name, presence: true
  has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.create(cocktail_params)
    if @cocktail.save
      redirect_to @cocktail
    else
      render(:new)
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :dose, :ingredient)
  end
end


# check strong params!

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    # or  @dose.cocktail_id = @cocktail.id
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render(:new)
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def new
    # @cocktail = Cocktail.find(params[:cocktail_id])
    @ingredient = Ingredient.new
  end

  def create
    # @cocktail = Cocktail.find(params[:cocktail_id])
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      redirect_to request.referrer
    else
      render(:new)
    end
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/index.html.erb
<h1>Cocktail Menu</h1>

<ul>
<% @cocktails.each do |cocktail| %>
  <li>
    <%= link_to cocktail [ 'name' ], cocktail_path(cocktail) %>
  </li>
<% end %>
</ul>

<p><%= link_to "Add a new cocktail", new_cocktail_path, class: "btn btn-primary" %></p>

app/views/cocktails/new.html.erb
<h1>Add a new cocktail</h1>

<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %></h1>


<h4>Ingredients and doses</h4>

<ul>
    <% @cocktail.doses.each do |dose| %>
      <li>
        <%= dose.description %>
        <%= dose.ingredient.name %>
        <%= link_to "delete", dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } %>
      </li>
    <% end %>
</ul>


<p><%= link_to "Add a dose", new_cocktail_dose_path(@cocktail), class: "btn btn-primary" %></p>

<p><%= link_to "Return to cocktail menu", cocktails_path, class: "btn btn-primary" %></p>

app/views/doses/new.html.erb
<h1>Add a new dose</h1>

<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

<%= link_to "Want to add a new ingredient?", new_ingredient_path, class: "btn btn-primary" %>
<!-- what if ingreident has more than one attribute? -->

app/views/ingredients/new.html.erb
<h1>Add a new ingredient</h1>

<%= simple_form_for @ingredient do |f| %>
  <%= f.input :name %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>